mysql:
  host: 127.0.0.1
  port: 3306
  database: go
  username: siebel
  password: 19960199

redis:
  host: 127.0.0.117
  port: 6379
  auth: 805345702

server:
  port: 8002

ftp:
  addr: 127.0.0.0:21
  username: selfspace
  password: 123546